name: create-pr-edge-next

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: create tag
        uses: mathieudutour/github-tag-action@v6.0
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: next
          default_bump: major
          release_branches: prod,staging
          append_to_pre_release_tag: rc
          dry_run: true

      - name: compile pull request
        id: compile_pr
        run: |
          output=$(ruby ./script/create-pr next edge) 
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=pr_body::$output"

      - name: create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [next]
          body: ${{ steps.compile_pr.outputs.pr_body }}
          source_branch: edge
          target_branch: next
          label: github-action