name: create-pr

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: create tag
        uses: anothrNick/github-tag-action@1.36.0
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: prod
          PRERELEASE_SUFFIX: rc
          WITH_V: true
          DRY_RUN: true


      - name: Create Pull Request
        run: ruby -r ./script/create-pr.rb ${{ steps.create_tag.outputs.new_tag }} next edge



#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
##          token: ${{ secrets.PAT }}
#          commit-message: ${{ steps.create_tag.outputs.new_tag }} | Release [Next]
#          committer: GitHub <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }} @users.noreply.github.com>
#          signoff: false
#          branch: ${{ inputs.branch }}
#          delete-branch: false
#          title:  ${{ steps.create_tag.outputs.new_tag }} | Release [Next]
#          body: |
#            Update report
#            - Updated *today's*
#            - Auto-generated by [create-pull-request]
#
#          labels: |
#            automated pr
##          assignees: peter-evans
##          reviewers: peter-evans
##          team-reviewers: |
##            owners
##            maintainers
##          milestone: 1
##          draft: false