name: create-pr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
#      - uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

      - name: create Tag
        uses: anothrNick/github-tag-action@1.36.0
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: prod,staging
          PRERELEASE_SUFFIX: rc
          WITH_V: true
          DRY_RUN: true

#      - name: compile Pull Request
#        id: compile_pr
##        run: ruby ./script/create-pr ${{ steps.create_tag.outputs.new_tag }}
#        run: ruby ./script/create-pr

      - name: Create Pull Request | Edge to Next
        if: ${{ github.ref == 'refs/heads/next' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [Next]
#          body: ${{ steps.compile_pr.output }}
          get_diff: true
          source_branch: edge
          target_branch: next

      - name: Create Pull Request | Next to Staging
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [Staging]
#          body: ${{ steps.compile_pr.output }}
          get_diff: true
          source_branch: next
          target_branch: staging

      - name: Create Pull Request | Staging to Prod
        if: ${{ github.ref == 'refs/heads/prod' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [Prod]
#          body: ${{ steps.compile_pr.output }}
          get_diff: true
          source_branch: staging
          target_branch: prod