name: create-pr-from

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: create tag
        uses: anothrNick/github-tag-action@1.36.0
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: prod,staging,next
          PRERELEASE_SUFFIX: rc
          WITH_V: true
          DRY_RUN: true

      - name: compile pull request
        id: compile_pr
        run: |
          output=$(ruby ./script/create-pr) 
          echo "::set-output name=pr_body::$output"

      - name: create pull request | edge to next
        if: ${{ github.ref == 'refs/heads/edge' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [Next]
          body: ${{ steps.compile_pr.outputs.pr_body }}
          get_diff: false
          source_branch: edge
          target_branch: next
          label: github-action

      - name: create pull request | next to staging
        if: ${{ github.ref == 'refs/heads/next' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }}.staging | Release [Staging]
          body: ${{ steps.compile_pr.outputs.pr_body }}
          get_diff: false
          source_branch: next
          target_branch: staging
          label: github-action

      - name: create pull request | staging to prod
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [Prod]
          body: ${{ steps.compile_pr.outputs.pr_body }}
          get_diff: false
          source_branch: staging
          target_branch: prod
          label: github-action