name: create-pr-staging-prod

on:
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - create-pr-staging-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: create tag
        uses: FritzViljoen/github-tag-action@1.36.1
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: prod,staging
          PRERELEASE_SUFFIX: rc
          WITH_V: true
          DRY_RUN: true
          CURRENT_BRANCH: prod

      if: ${{ steps.create_tag.outputs.new_tag }} != ""
      - name: compile pull request
        id: compile_pr
        run: |
          output=$(ruby ./script/create-pr prod staging) 
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=pr_body::$output"

      - name: create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.create_tag.outputs.new_tag }} | Release [prod]
          body: ${{ steps.compile_pr.outputs.pr_body }}
          source_branch: staging
          target_branch: prod
          label: github-action