name: release-next

on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - next

jobs:
  build:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'github-action')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: create tag
        uses: FritzViljoen/github-tag-action@1.36.1
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
          RELEASE_BRANCHES: prod,staging
          PRERELEASE_SUFFIX: rc
          WITH_V: true

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create_tag.outputs.new_tag }}
          name: ${{ steps.create_tag.outputs.new_tag }} | Release [${{ GITHUB_REF##*/ }}]
          generateReleaseNotes: false
          body: ${{ github.event.pull_request.body }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

