name: release-staging

on:
  pull_request:
    types: closed
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: get tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.current_tag.outputs.tag }}.${{ github.base_ref }}
          name: ${{ steps.current_tag.outputs.tag }}.${{ github.base_ref }} | Release [${{ github.base_ref }}]
          generateReleaseNotes: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: true

      - name: update pull request
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          title-update-action: replace
          title-template: ${{ steps.current_tag.outputs.tag }}.${{ github.base_ref }} | Release [${{ github.base_ref }}]
          body-update-action: 'prefix'
          body-template: |
            Merging into ${{ github.base_ref }}